### ISSUE TITLE
Dependency missing from readme

### ISSUE THREAD

**Issue by dUmich** [jkruppa/kmerPyramid#1]
I noticed the dependency ‘ShortRead’ is not mentioned in the readme but is required to install kmerPyramid. Could this be mentioned? 

source("http://bioconductor.org/biocLite.R")
biocLite("ShortRead")

**Comment by jkruppa** [comment]
Hi,

thank you very much. I have added it to the Readme and we will do some more text after the weekend.

Best wishes

Jochen
